name = "xpengmedia-iptv-proxy"
main = "cloudflare-worker-proxy.js"
compatibility_date = "2024-11-18"
workers_dev = true

# Configuration du worker
[env.production]
name = "xpengmedia-iptv-proxy"
